services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  MRG\Dashbash\:
    resource: '../Classes/*'

  MRG\Dashbash\Widgets\CTypesWidget:
    public: true
    arguments:
      $configuration: '@dashboard.views.widget'
      $view: '@dashboard.views.widget'
      $siteFinder: '@TYPO3\CMS\Core\Site\SiteFinder'
    tags:
      - name: dashboard.widget
        identifier: 'ctypes'
        groupNames: 'systemInfo'
        title: 'Anzahl der Inhaltselemente in den jeweiligen Sprachen'
        description: 'Zeigt die Anzahl der verschiedenen CTypes und der verwendeten Sprachen'
        iconIdentifier: 'content-widget-dashbash'
        height: 'medium'
        width: 'medium'
        additionalCssClasses: 'dashboard-item--dashbash'

  dashboard.widget.ctypes:
    class: 'MRG\Dashbash\Widgets\CTypesWidget'
    arguments:
      $view: '@dashboard.views.widget'
