services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  MRG\Dashbash\:
    resource: '../Classes/*'

  dashboard.widget.ctypes:
    class: 'MRG\Dashbash\Widgets\CTypesWidget'
    arguments:
      $view: '@dashboard.views.widget'
    tags:
      - name: dashboard.widget
        identifier: 'ctypes'
        groupNames: 'general'
        title: 'LLL:EXT:dashbash/Resources/Private/Language/locallang.xlf:widget.ctypes.title'
        description: 'LLL:EXT:dashbash/Resources/Private/Language/locallang.xlf:widget.ctypes.description'
        iconIdentifier: 'content-widget-chart'
        height: 'medium'
        width: 'medium'
