services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  MRG\Dashbash\:
    resource: '../Classes/*'

  MRG\Dashbash\Widgets\CTypesWidget:
    public: true
    arguments:
      $configuration: '@dashboard.views.widget'
      $view: '@dashboard.views.widget'
      $siteFinder: '@TYPO3\CMS\Core\Site\SiteFinder'
    tags:
      - name: dashboard.widget
        identifier: 'ctypes'
        groupNames: 'general'
        title: 'CTypes and Languages Overview'
        description: 'Shows the count of different CTypes and used languages'
        iconIdentifier: 'content-widget-chart'
        height: 'medium'
        width: 'medium'

  dashboard.widget.ctypes:
    class: 'MRG\Dashbash\Widgets\CTypesWidget'
    arguments:
      $view: '@dashboard.views.widget'
